# Zero/One

Run the source code:

In [77]:
%run "code\zeroone.py"

## Example 4.1

The following code demonstrates the model with the small input, created using the `text_to_tensor()` and `space_pad()` functions. The `text` string input can be modified. The output of the model is a sequence $\left\{\pmb{q}_t\right\}_{t=1}^T$ as described in chapter 4; if the sequence length is greater than 25 then the transpose is printed to keep the output to a sensible number of lines.

In [158]:
text = 'test with zero and one'

textt = text_to_tensor(space_pad(text))
M = make_rnn_model()
out = M.predict(textt, verbose=0)
if out.shape[1] <= 25:
    print(out)
else:
    print(out.reshape(out.shape[1],2).T)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [1. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 1.]]]


The code below shows the hidden state of the recurrent layer; best viewed for outputs from an input string of less than 25 characters.

In [160]:
M_hidden = tf.keras.Model(inputs=M.input, outputs=M.layers[1].output)
out = M_hidden.predict(textt, verbose=0)
if out.shape[1] <= 25:
    print(out)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]]


## Example 4.2

The following code demonstrates the model with the full input, created using the `text_to_onehot()` and `space_pad()` functions. The `text` string input can be modified. The output of the model should be the same as Example 4.1 if the same input `text` is used.

In [161]:
text = 'test with zero and one'

textt = text_to_onehot(space_pad(text))
Mf = make_full_rnn_model()
out = Mf.predict(textt, verbose=0)
if out.shape[1] <= 25:
    print(out)
else:
    print(out.reshape(out.shape[1],2).T)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [1. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 1.]]]
