# Boolean

Run the source code:

In [5]:
%run "code\bool.py"

## Example 2.1

Modify `u` and `x` to create a Boolean function $\mathbb{R}^2 \rightarrow \mathbb{R}$ defined by `u`, and evaluate it at `x`.

In [6]:
# Specify u in {0,1}^4 and x in {0,1}^2
u = [0,1,1,0]
x = [0,0]

u = np.array(u)
x = tf.convert_to_tensor(np.array(x).reshape(1,2))
M = make_u_model(u=u)
print(M.predict(x,verbose=0)) 


[[0.]]


Show the weights for the first (ReLU) layer. Note that `tf.layers.Dense` uses the transpose of what we have described in the text.

In [7]:
print(f"W = \n {M.layers[1].get_weights()[0]}")
print(f"b = \n {M.layers[1].get_weights()[1]}")

W = 
 [[0. 1. 1.]
 [1. 0. 1.]]
b = 
 [ 0.  0. -1.]


Show the weights for the second layer. It should be clear that the weights are equal to $\left(u_2 - u_0\right)$, $\left(u_1 - u_0\right)$, and $\left(u_3 - u_2 - u_1 + u_0\right)$, and the bias is $u_0$.

In [8]:
print(f"u = \n {u}")
print(f"W = \n {M.layers[2].get_weights()[0]}")
print(f"b = \n {M.layers[2].get_weights()[1]}")

u = 
 [0 1 1 0]
W = 
 [[ 1.]
 [ 1.]
 [-2.]]
b = 
 [0.]


## Example 2.2

Now experiment by building Boolean functions $\mathbb{R}^n \rightarrow \mathbb{R}$. Modify `n` to change the dimension of the input domain. The code then builds the model using the generalization of example 2.1 for a random $u \in \left\{0, 1\right\}^n$.

The model summary shows the number of parameters in each layer, and the model model is evaluated on all elements of the input domain to verify that it returns the corresponding element of $u$ in every case.

In [9]:
# Specify an integer between 2 and 8 for practical run time
n = 4

k = 2**n
u = 1 * (np.random.random(k) >= 0.5)
print(f"u = {u}")
M = make_u_model(u=u)
x_all = np.array(list(itertools.product(*[[0,1]]*n)))
M.summary()
print(f"[loss, accuracy] = {M.evaluate(x_all, u.reshape(k,1), verbose=0)}")

u = [0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 1]
Model: "u_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_4 (Dense)             (None, 15)                75        
                                                                 


 dense_5 (Dense)             (None, 1)                 16        
                                                                 
Total params: 91
Trainable params: 91
Non-trainable params: 0
_________________________________________________________________
[loss, accuracy] = [0.0, 1.0]


## Example 2.3

We now create the model that builds and evaluates all Boolean functions $\mathbb{R}^n \rightarrow \mathbb{R}$ given $n$. Modify `n` to be 2, 3, or 4; any greater value will require too many parameters to store in memory. The model summary and evaluation are the same as the previous example.

In [7]:
# Specify n=2,3,4
n = 4

M = make_n_model(n=n)
x_all = np.array(list(itertools.product(*[[0,1]]*n)))
y_all = np.array(list(itertools.product(*[[0,1]]*(2**n)))).T
M.summary()
print(f"[loss, accuracy] = {M.evaluate(x_all, y_all, verbose=0)}")

Model: "n_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_6 (Dense)             (None, 15)                75        
                                                                 
 dense_7 (Dense)             (None, 65536)             1048576   
                                                                 
Total params: 1,048,651
Trainable params: 1,048,651
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 207ms/step - loss: 0.0000e+00 - accuracy: 1.0000
[loss, accuracy] = [0.0, 1.0]
